server:
  port: 8081

spring:
  datasource:
    username: root
    password: qwertyuiop233
    url: jdbc:mysql://localhost:3306/ssm_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
  servlet:
    multipart:
      max-file-size: 10MB

logging:
  level:
    com.yxz: debug

mybatis-plus:
  mapper-locations:
    classpath:mapper\*.xml
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
