name: Build and Package

on:
  push:
    branches:
      - main  # 触发条件可以根据需要调整

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn clean package -DskipTests  # 执行Maven打包，跳过测试

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-application
          path: target/*.jar  # 将生成的JAR文件发布为Artifact，路径根据实际情况调整
